language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -U pytest-cov

# disable shallow clone
git:
  depth: false

addons:
  sonarcloud:
    organization: "mnbf9rca-github" # the key of the org you chose at step #3
    token:
      secure: Af/RkcHu8PH67HmYqig0fduxXys4LmEht3rZx51qgaYHuiWim5TeGDZqfoFxF4u8cYOSlNxhxPQtk1wXBggAGoo6NdpjGcGq8JBc1T4Tuy8K19sw/iOtKqYasQPuVvVefWZtLnbEtWn9vpl3KgJdHexeK/rqzckLeVNsY7rH4sBQPeG3YuU2sRfX3/nRt4On1x7DY+8DM0N4bH1FQCy9pIoajUzCbtIMOp3n3TWAu6JofMW8TTSmIQXvBNQuDffVcdZztE5hIc5hF0XzpeQXNTWpfz+xNPyNVt/yB3+ruY4mSU0jL0TI87kcqzIO2uO2LZYLUk/U+ndPeSPB0hjaiaqcgzOiZQI3x7Wh91gzxo2IEuz1r/RZdvK3eHtBs8qCO1vlD82L6xsObxwWkc71cLiPvGw9qnz0eThv7LPXMIi8uATTjVXDrLNE7IlCMdlTfp6Y+mjXV7h3r8rAp0alcly0YpN0XZHSsVRLjzfO9Eqo5+niUS+thLanLkLr5WOkPEbEKVs/vhPbinzzjxQDYiScwLf8GwzQq1pnsfBXYyUKsbKRRiz1LEzQn5r99ux5QZ02mPO1V3KNneOwoB/6ZMyG4axDLMcsaNJn0oIXgoXC8ZGfHMofGZZnOztyLsS+sPqpRdGBTGtlTHPyYl+CgMQF0q664if86uiQwqlqQNE=
      # secure: QlmNySQQDcHKNXOHduyQxwoSTh0tLpCuYGLWs7yOz8OOER2opYeIEg6JAcDhbbTCWwuwxvjaN6SsPvzoO3Ghk9NMofPYdGzfvkgELsHYyfC8fbvNn2NNfTT1g6EiLKRzq5NziWPWazW876bFaNsoS1rUpxdTx4oQ8aFxL3HRQE2G41GWoAHrw5UN2cyxHNzXFQCWLiBk/8/0u5/F7ZOlDE0m6mmv/ljbxUt8QLdcW9dQmdTti8i1GwunCwlTGCqT/XtWUCII8SLAuxRLYqk7Vq8Y2+hnJPbYURQB6gOjfv1qrn7oC6mOuPnf48e1dnsEzxg3wRSAGsJSuMzHpAAfZZ4ytRxs64yocXexDYNpfuGr6pDLvOBcX6QZgNq+nARhJC0iBEEq54kBmRhZqclqOVZKx33t8/EXAx5ktx9/ZxFFA3EPsy6JQbSvtlno2vSl31OE/me1HioR1ThjZ7vneCyZutqFqWRwexcH/bUCDKAlcIpVsmLhVm9GLIN2N3dm8X81XOHOhoL6BPWR9zcJII+Q2Q1M9JSGN1ZnGFgWcIAt5/W4OO3/uzVSgNOuO0ntoJ99NM2K0/tInqADdtbjJz3zEZ0PoKMQpDlrb+FiRT+tjJALv6R2/+SZCtLy5JY/E5onqxOYjLiAR/eIGPlYjCJwZnFM+hdTGw2amasEmlw=
script:
  - pytest -v --cov --cov-report=xml:coverage.xml
  - sonar-scanner -X