runtime: python
env: flex
entrypoint: gunicorn -b :$PORT application:app

runtime_config:
    python_version: 3

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10


# https://cloud.google.com/memorystore/docs/redis/connect-redis-instance-flex
network:
  name: default

env_variables:
    REDIS_HOST: 10.0.0.4
    REDIS_PORT: 6379
    SQLALCHEMY_DATABASE_URI: >-
      mysql+pymysql://<creds>@/poohead?unix_socket=/cloudsql/pooheadcardgame:europe-west1:poohead-db
    

beta_settings:
    cloud_sql_instances: pooheadcardgame:europe-west1:poohead-db