#!/usr/bin/env python3

from cards import Card, Deck
from game import Game

g = Game(["rob","sam"])



g.deal()

for p in g.players:
    print(p.name)
    for c in p.face_down:
        print(c)

print(len(g.deck))
for c in g.deck:
    print(c)
